#cloud-config
repo_update: true
repo_upgrade: all

write_files:
  - path: /home/ubuntu/.env
    permissions: '0666'
    content: |
      AIG_LOG_LEVEL=debug
      PWD=/home/ubuntu

  - path: /etc/docker/config.json
    permissions: '0666'
    content: |
      {
        "insecure-registry": "localhost"
      }

  - path: /etc/systemd/system/aigateway.service
    permissions: '0666'
    content: |
      [Unit]
      Description=AI Gateway services
      After=docker.service
      Requires=docker.service

      [Service]
      Type=simple
      EnvironmentFile=/home/ubuntu/.env
      Environment=COMPOSE_FILE=/home/ubuntu/docker-compose.yml
      ExecStartPre=-/usr/local/bin/docker-compose -f ${COMPOSE_FILE} down
      ExecStart=/usr/local/bin/docker-compose -f ${COMPOSE_FILE} up --force-recreate --abort-on-container-exit
      ExecStop=/usr/local/bin/docker-compose -f ${COMPOSE_FILE} down
      Restart=always
      RestartSec=60s

      [Install]
      WantedBy=multi-user.target

runcmd:
  - apt-get remove -y docker docker-engine docker.io
  - apt-get install curl apt-transport-https ca-certificates software-properties-common
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
  - add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - apt-get update
  - apt-get install -y docker-ce
  - curl -L https://github.com/docker/compose/releases/download/1.27.4/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
  - chmod +x /usr/local/bin/docker-compose
  - usermod -aG docker ubuntu
  - systemctl enable docker
  - systemctl start docker
  - echo 'AIG_API_ENDPOINT=http://'$( curl -s http://169.254.169.254/latest/meta-data/public-ipv4 ) >> /home/ubuntu/.env
  - curl -L https://s3-ap-northeast-1.amazonaws.com/ai-gateway/docker-compose.yml -o /home/ubuntu/docker-compose.yml
  - systemctl enable aigateway
  - systemctl start aigateway
  - docker pull aigateway/singularity:2.6-d2s
  - docker pull tensorflow/tensorflow:2.3.2
