version: "2.4"

services:

  api:
    image: aigateway/api:local
    build:
      context: ../../
      dockerfile: tools/prod/api.Dockerfile
      args:
        BASE_IMAGE: aigateway/api:cache
      target: builder
    entrypoint: tini -- sleep 31536000
    ports:
      - 9000:80
    environment:
      - AIG_RESCALE_ENDPOINT=https://platform.rescale.jp
      - AIG_RESCALE_API_TOKEN
      - AIG_LOG_LEVEL=debug
      - AIG_LOG_FORMAT=json
      - AIG_MAX_WORKERS=4
      - AIG_MUST_SIGN_IN=false
      - AIG_IMAGES_TOBE_IGNORED=aigateway/,aig-jupyter/,supinf/,<none>
      - AIG_WORKSPACE_HOST_DIR=${PWD}/tools/dev/tmp/work
      - AIG_SINGULARITY_HOST_DIR=${PWD}/tools/dev/tmp/simg
      - AIG_DATABASE_ENDPOINT=user:pass@tcp(aigateway_db:3306)/aigateway?charset=utf8mb4&collation=utf8_unicode_ci&parseTime=true
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - ../../api/certs:/certs
      - ./tmp/db:/tmp/badger
      - ./tmp/simg:/tmp/simg
      - ./tmp/work:/tmp/work
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /go/src/github.com/xtream-d-labs/ai-gateway/api/src
    networks:
      - services
    restart: always
    container_name: aigateway_api

  web:
    image: supinf/hugo:0.x
    command: server --bind=0.0.0.0 -p=80 -b=http://localhost:8080/ --appendPort=false --disableLiveReload
    volumes:
      - ../../web/src:/app
    logging:
      driver: none
    networks:
      - services
    restart: always
    container_name: aigateway_web

  proxy:
    image: aigateway/proxy:1.11
    ports:
      - 8080:80
    logging:
      driver: none
    networks:
      - services
    restart: always
    container_name: aigateway_proxy

  gulp:
    image: aigateway/gulp:local-20191003
    build: docker/gulp
    volumes:
      - ../../web:/monitor/web
      - /var/run/docker.sock:/var/run/docker.sock
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"
    ulimits:
      cpu:
        soft: 20
        hard: 40
    networks:
      - services
    restart: always
    container_name: aigateway_gulp

networks:
  services:
    external:
      name: dev_aigateway_network
