#cloud-config
repo_update: true
repo_upgrade: all

packages:
  - docker

write_files:
  - path: /home/ec2-user/.env
    permissions: '0666'
    content: |
      SS_LOG_LEVEL=info
      PWD=/home/ec2-user

  - path: /etc/sysconfig/docker
    permissions: '0666'
    content: |
      DAEMON_MAXFILES=1048576
      OPTIONS="--default-ulimit nofile=1024:4096 --insecure-registry localhost"
      DAEMON_PIDFILE_TIMEOUT=10

  - path: /etc/systemd/system/aigateway.service
    permissions: '0666'
    content: |
      [Unit]
      Description=AI Gateway services
      After=docker.service
      Requires=docker.service

      [Service]
      Type=simple
      EnvironmentFile=/home/ec2-user/.env
      Environment=COMPOSE_FILE=/home/ec2-user/docker-compose.yml
      ExecStartPre=-/usr/local/bin/docker-compose -f ${COMPOSE_FILE} down
      ExecStart=/usr/local/bin/docker-compose -f ${COMPOSE_FILE} up --force-recreate --abort-on-container-exit
      ExecStop=/usr/local/bin/docker-compose -f ${COMPOSE_FILE} down
      Restart=always
      RestartSec=60s

      [Install]
      WantedBy=multi-user.target

runcmd:
  - curl -L https://github.com/docker/compose/releases/download/1.27.4/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
  - chmod +x /usr/local/bin/docker-compose
  - usermod -aG docker ec2-user
  - systemctl enable docker
  - systemctl start docker
  - echo 'SS_API_ENDPOINT=http://'$( curl -s http://169.254.169.254/latest/meta-data/public-ipv4 ) >> /home/ec2-user/.env
  - curl -L https://s3-ap-northeast-1.amazonaws.com/ai-gateway/docker-compose.yml -o /home/ec2-user/docker-compose.yml
  - systemctl enable aigateway
  - systemctl start aigateway
  - docker pull aigateway/singularity:2.6-d2s
  - docker pull tensorflow/tensorflow:2.3.0
  - docker pull mxnet/python:1.5.0_cpu_py3
  - docker pull chainer/chainer:v7.7.0-intel-python3
